export enum Role {
  // Basic
  DASHBOARD = 'DASH',
  Admin = 'admin',
  User = 'user',
  SuperUser = 'superuser',
  USER = 'USR',
  CUSTOMER = 'CUST',
  VENDOR = 'VEND',

  // KDocs
  KD_EXPORTS = 'EXP',
  IMPORTS = 'IMP',
  MINISTOCK = 'MST',
  KD_LOCALSALES = 'LSAL',
  KD_LOCALSALESRETURN = 'LSAR',
  LOCALISATION = 'TXN',

  // User
  DOCUMENTAPPROVAL = 'DOCAPV',
  MYDOCUMENTS = 'MYDOC',
  USERSETTING = 'USRSET',

  // Accounting
  ACCOUNTREAD = 'ACCR',
  ACCOUNTCREATE = 'ACCC',
  ACCOUNTUPDATE = 'ACCU',
  ACCOUNTDELETE = 'ACCD',

  // Journal Entry
  JOURNALENTRYCREATE = 'JEC',
  JOURNALENTRYUPDATE = 'JEU',
  JOURNALENTRYDELETE = 'JED',
  JOURNALENTRYREAD = 'JER',
  JOURNALENTRYDRAFT = 'JEDF',

  INCOMESTATEMENT = 'IS',
  CASHFLOWSTATEMENT = 'CFS',
  ACCOUNTSBALANCESHEET = 'ABS',
  ACCOUNTSTRIALBALANCE = 'ATB',

  // HR
  STATICFIELD = 'SF',
  DOCUMENTTEMPLATE = 'DOCTEMP',
  DOCUMENTGENERATION = 'DOCGEN',
  ALLOWANCEREQUESTLIST = 'ARL',
  HRUSERLIST = 'HRL',
  LEAVEREQUESTLIST = 'LRL',
  OVERTIMEAPPROVALLIST = 'OAL',
  FILEAPPROVALLIST = 'FAL',

  // customer statement
  CUSTOMERSTATEMENTCREATE = 'CSC',
  CUSTOMERSTATEMENTUPDATE = 'CSU',
  CUSTOMERSTATEMENTDELETE = 'CSD',
  CUSTOMERSTATEMENTREAD = 'CSR',

  // stock management - product styles
  PRODUCTSTYLECREATE = 'PSC',
  PRODUCTSTYLEUPDATE = 'PSU',
  PRODUCTSTYLEDELETE = 'PSD',
  PRODUCTSTYLEREAD = 'PSR',

  // stock management - memo-in
  MEMOINCREATE = 'MMIC',
  MEMOINUPDATE = 'MMIU',
  MEMOINDELETE = 'MMID',
  MEMOINREAD = 'MMIR',

  // stock management - stock
  STOCKCREATE = 'STC',
  STOCKUPDATE = 'STU',
  STOCKDELETE = 'STD',
  STOCKREAD = 'STR',
  STOCKTRANSFER = 'STT',

  // stock management - local sale
  // STOCKLOCALSALECREATE = 'SLSC',
  // STOCKLOCALSALEUPDATE = 'SLSU',
  // STOCKLOCALSALEREAD = 'SLSR',
  // STOCKLOCALSALEDELETE = 'SLSD',
  // STOCKLOCALSALES = 'SLSAL',
  // STOCKLOCALSALESRETURN = 'SLSAR',

  EXCHANGERATE = 'EXR',
  EVENTS = 'EVT',

  // sales
  LOCAL_SALES = 'LS',
  EXPORTS_SALES = 'ES',
  LOCAL_SHOW_SALES = 'LSS',
  FOREIGN_SHOW_SALES = 'FSS',
  USED_JEWELLERY_SALES = 'UJS',
  TAX_FREE_SALES = 'TFS',

  // sales return
  LOCAL_SALES_RETURN = 'LSR',
  EXPORTS_SALES_RETURN = 'ESR',

  // Attendeance
  ATTENDANCECREATE = 'ATTC',
  ATTENDANCEUPDATE = 'ATTU',
  ATTENDANCEDELETE = 'ATTD',
  ATTENDANCEREAD = 'ATTR',
  ATTENDANCEINOUT = 'ATTIO',
  ATTENDANCEMANAGE = 'ATTM',

  DAILYATTENDANCE = 'DA',
  // sale return
  SALERETURNCREATE = 'LSRC',
  SALERETURNUPDATE = 'LSRU',
  SALERETURNDELETE = 'LSRD',
  SALERETURNREAD = 'LSRR',

  SALERETURNINVOICELIST = 'SRIL',

  //Holiday Template
  HOLIDAYTEMPLATECREATE = 'HOLTC',
  HOLIDAYTEMPLATEUPDATE = 'HOLTU',
  HOLIDAYTEMPLATEDELETE = 'HOLTD',
  HOLIDAYTEMPLATEREAD = 'HOLTR',

  //contract template
  CONTRACTTEMPLATECREATE = 'CONTC',
  CONTRACTTEMPLATEUPDATE = 'CONTU',
  CONTRACTTEMPLATEDELETE = 'CONTD',
  CONTRACTTEMPLATEREAD = 'CONTR',

  // order sheet
  ORDERSHEETCREATE = 'OSC',
  ORDERSHEETUPDATE = 'OSU',
  ORDERSHEETDELETE = 'OSD',
  ORDERSHEETREAD = 'OSR',

  // branch
  BRANCHREAD = 'BRL',
  BRANCHCREATE = 'BRC',
  BRANCHUPDATE = 'BRU',
  BRANCHDELETE = 'BRD',

  // Repairing
  REPAIRINGCREATE = 'RPC',
  REPAIRINGUPDATE = 'RPU',
  REPAIRINGDELETE = 'RPD',
  REPAIRINGREAD = 'RPR',
}
